language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t slothness7/docker-course -f Dockerfile.dev .

script:
  - docker run -e CI=true slothness7/docker-course yarn run test -- --coverage